version: '3'
services:
  builder:
#   image: "kristall-ci:1.0"
    build: .
    volumes:
      - ./output:/artifacts
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined

